### ISSUE TITLE
esp32-arduino support? (IDFGH-13622)

### ISSUE THREAD

**Issue by vicatcu** [espressif/esp-mqtt#285]
Can you provide some instruction for how to use this library in the Arduino environment? This library code used to be included "natively" in the esp32-arduino board support package in the 2.x release, but that seems to have changed in the current 3.x (current stable 3.0.4) code base.

**Comment by rftafas** [comment]
Hi,

It's already part of the Arduino Core for ESP32, so maybe check some configs? Can you try `#include "mqtt_client.h"`?

I suggest closing this issue here. For future questions, it is better (and faster) to concentrate Arduino-ESP32 questions [here](https://github.com/espressif/arduino-esp32/issues).

**Comment by vicatcu** [comment]
Closing, still haven't figured out how to get it to build
